### ISSUE TITLE
UDP and GET_TIME

### ISSUE THREAD

**Issue by MaxPlap** [xlar54/ultimateii-dos-lib#50]
I'm trying to write a NTP interrogation tool. To achieve that I added the UDP support to this library.
I also noticed in [network_target.h](https://github.com/markusC64/1541ultimate2/blob/master/software/io/network/network_target.h) there is no discrimination on TCP vs UDP methods towards sockets, except for creating them.
I added: `uii_udpconnect`, `uii_get_time` and refactored method names to mirror network_target.h in [my fork](https://github.com/MaxPlap/ultimateii-dos-lib/tree/new-functions). 

I hope I have been helpful

**Comment by MaxPlap** [comment]
Added a test [repo](https://github.com/MaxPlap/ntp2ultimate) for both UDP packets and Time functions

**Comment by xlar54** [comment]
Excellent, thanks for your contribution!    From: MaxPlapSent: Thursday, January 21, 2021 12:51 PMTo: xlar54/ultimateii-dos-libCc: SubscribedSubject: Re: [xlar54/ultimateii-dos-lib] UDP and GET_TIME (#50) Added a test repo for both UDP packets and Time functions—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by sblendorio** [comment]
Merged into main repo. Thanks!

**Comment by MaxPlap** [comment]
it works flawlessy now!
